### ISSUE TITLE
estimagic logging

### ISSUE THREAD

**Issue by peisenha** [structExpectations/analysis#5]
Use logging provided by `estimagic` wherever possible, see https://estimagic.readthedocs.io/en/latest/optimization/logging.html

**Comment by boryana-ilieva** [comment]
I just talked to Janos, python optimised estimagic logging db query will only be available in the next release of estimagic for nlopt. Maybe we should wait for that before I write an sql/python code to query the data base (Janos also said, the form of the data base is changing quite e bit with the new release).
I would prepare some code on what stats we want to look at when the new release is ready: like how much of the parameter space is being explored, which parameters seem to influence the fit most, etc.
